; This file was auto-generated by drush make
api = 2
core = 7.x

; Modules

projects[libraries][subdir] = "contrib"
projects[libraries][version] = "2.1"

projects[macro][subdir] = "contrib"
projects[macro][version] = "1.0-alpha2"

projects[patterns][subdir] = "contrib"
projects[patterns][version] = "2.0"

projects[token][subdir] = "contrib"
projects[token][version] = "1.5"

; Libraries

; Spyc (YAML parser): required by patterns_yamlparser submodule
libraries[spyc][download][type] = "get"
libraries[spyc][download][url] = "https://raw.github.com/mustangostang/spyc/master/Spyc.php"
libraries[spyc][directory_name] = "spyc"
libraries[spyc][type] = "library"

; Codemirror (editor): optional for patterns
libraries[codemirror][download][type] = "git"
libraries[codemirror][download][url] = "https://github.com/marijnh/CodeMirror.git"
libraries[codemirror][directory_name] = "codemirror"
libraries[codemirror][type] = "library"
